### ISSUE TITLE
Region should probably be set in a .env file

### ISSUE THREAD

**Issue by zbruhnke** [z0ph/aws-security-toolbox#2]
https://github.com/z0ph/aws-security-toolbox/blob/30fa2473065bac6c546391e39ee55b02c00cb9e8/Dockerfile#L7

Nowhere in the README is this clear that you're defaulting to this region, if this project takes up any real adoption this could cause confusion for people.

My suggestion would be to default to grabbing this from a .env file and to check in a .env.example file to the repo so that people know to set a default region

**Comment by z0ph** [comment]
Hi Zach,

Thanks for this proposition, will do this ASAP. Your right, most of users will not use `eu-west-1`

**Comment by z0ph** [comment]
Fixed in v0.2: https://github.com/z0ph/aws-security-toolbox/tree/v0.2
